package org.jetbrains.compose.swing.window

import java.awt.Window

/**
 * Top-left position of a window or dialog on the screen, in raw pixels.
 *
 * A position is either concrete coordinates ([Absolute]) or a request to place the window
 * ([PlatformDefault], [CenteredOnScreen], [CenteredOnOwner], [CenteredOn]). A request carries no
 * coordinates of its own, and the placement it resolves to is written back into the driving state as an
 * [Absolute] position.
 */
public sealed interface WindowPosition {
    /**
     * The window has not been placed yet, so the platform positions it.
     *
     * Meaningful only before the window is shown: once a window is visible it always has concrete
     * coordinates and can no longer return to [PlatformDefault].
     */
    public object PlatformDefault : WindowPosition {
        override fun toString(): String = "PlatformDefault"
    }

    /**
     * The window is centered on the screen, within the area the platform leaves usable by task bars
     * and menu bars.
     *
     * Declaring it again re-centers the window, whether or not it is already shown.
     */
    public object CenteredOnScreen : WindowPosition {
        override fun toString(): String = "CenteredOnScreen"
    }

    /**
     * The window is centered on the window that owns it, or on the screen when it has no owner. An
     * owner that is not on screen yet centers the window on the owner's screen instead of on the
     * owner's bounds.
     *
     * Declaring it again re-centers the window, whether or not it is already shown.
     */
    public object CenteredOnOwner : WindowPosition {
        override fun toString(): String = "CenteredOnOwner"
    }

    /**
     * The window is centered on [window], whatever the relation between the two. A [window] that is not
     * on screen yet centers the window on that window's screen instead of on its bounds.
     *
     * The centering happens as the position is applied, on the bounds [window] holds at that moment, so
     * the window stands where it was put once [window] moves on. Declaring it again re-centers the
     * window, whether or not it is already shown.
     *
     * @property window the window whose bounds this window is centered on
     */
    public class CenteredOn(
        public val window: Window,
    ) : WindowPosition {
        override fun equals(other: Any?): Boolean = this === other || (other is CenteredOn && window == other.window)

        override fun hashCode(): Int = window.hashCode()

        override fun toString(): String = "CenteredOn(window=$window)"
    }

    /**
     * Absolute top-left position in pixels relative to the screen.
     *
     * @property x the horizontal position of the window, in pixels
     * @property y the vertical position of the window, in pixels
     */
    public class Absolute(
        public val x: Int,
        public val y: Int,
    ) : WindowPosition {
        // equals, hashCode and toString compare by coordinates, written by hand rather than generated by
        // a data class: a data class would also publish copy() and componentN(), both welded to this
        // exact constructor. A later coordinate would change copy()'s signature, and reordering x and y
        // would silently change what a destructuring declaration binds; adding a member as the class
        // stands changes neither.
        override fun equals(other: Any?): Boolean =
            this === other || (other is Absolute && x == other.x && y == other.y)

        override fun hashCode(): Int = 31 * x + y

        override fun toString(): String = "Absolute(x=$x, y=$y)"
    }
}
